### ISSUE TITLE
Complains of missing MySQL extension, which is there!

### ISSUE THREAD

**Issue by greencopper** [osCommerce/oscommerce#29]
Fresh download and installation. 

![oscommerce](https://cloud.githubusercontent.com/assets/1302896/10599340/80f99c16-7701-11e5-91bf-b800d4aa84bb.png)

**Comment by greencopper** [comment]
Never mind, didn't notice that this project is dead.

**Comment by BebZ** [comment]
It seems oscommerce community has vanished...

**Comment by acidvertigo** [comment]
Right place to open the issue is https://github.com/osCommerce/oscommerce2

**Comment by greencopper** [comment]
Thanks! Issue moved: https://github.com/osCommerce/oscommerce2/issues/368
